DROP TABLE IF EXISTS BOARDS;


CREATE TABLE BOARDS (
    BOARD_NUM INT PRIMARY KEY,
    BOARD_NAME VARCHAR(30) REFERENCES members(id) ON DELETE CASCADE,
    BOARD_PASS VARCHAR(30),
    BOARD_SUBJECT VARCHAR(300),
    BOARD_CONTENT VARCHAR(4000),
    BOARD_FILE VARCHAR(50),
    BOARD_ORIGINAL VARCHAR(50),
    BOARD_RE_REF INT,
    BOARD_RE_LEV INT,
    BOARD_RE_SEQ INT,
    BOARD_READCOUNT INT,
    BOARD_DATE VARCHAR(10) NOT NULL DEFAULT DATE_FORMAT(CURRENT_DATE, '%Y/%m/%d'),
    BOARD_LIKE INT,
    BOARD_NOTICE VARCHAR(5) CHECK (BOARD_NOTICE IN ('true', 'false')),
    fontColor VARCHAR(15),
    fontSize VARCHAR(15),
    fontWeight INT
);






    
   





    
   